### ISSUE TITLE
Invitation to contribute to Phoenix examples organization

### ISSUE THREAD

**Issue by yedhukrishnan** [gogogarrett/phoenix_crud#6]
Hi.. Thanks for creating such a great example app for Phoenix :) We have created an organization for Phoenix example apps. You can see it here: https://github.com/phoenix-examples

I would like to know if you are interested to be a part of it. If yes, I'll create a repo for you so that you can push this to it. Also, let me know if you are interested to be an owner the organization so that you help us with reviewing the apps submitted by other users.

**Comment by gogogarrett** [comment]
Thanks! That would be great. I can work on updating it as well to the newest version of Phoenix as this is a bit out of date.

**Comment by yedhukrishnan** [comment]
Awesome! I'll invite you to the organization. You can create a repo and push it.
